language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t coolasshonky/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true coolasshonky/react-test npm test

after_success:
  - docker build -t coolasshonky/multi-client ./client
  - docker build -t coolasshonky/multi-server ./server
  - docker build -t coolasshonky/multi-nginx ./nginx
  - docker build -t coolasshonky/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login - u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push coolasshonky/multi-client
  - docker push coolasshonky/multi-server
  - docker push coolasshonky/multi-nginx
  - docker push coolasshonky/multi-worker